### ISSUE TITLE
True-color support

### ISSUE THREAD

**Issue by dustinlacewell** [gvalkov/python-ansimarkup#1]
Some way to do arbitrary RGB or Hex based tags would be super nice.

**Comment by gvalkov** [comment]
Added very basic and unchecked support in 586483a34ba226101ef29ebd396f2d127c13e9af. From the readme:

```
# Xterm, hex and rgb colors are accepted by the <fg> and <bg> tags.
parse("<fg 86>aquamarine foreground</fg 86>")
parse("<bg #00005f>dark blue background<bg #00005f>")
parse("<fg 0,95,0>dark green foreground<fg 0,95,0>")
```

What probably also needs to be fixed:
- Approximating from rgb to xterm colors.
- Shorthand hex colors (e.g. `#fff`).
- All hex and rgb tuple input is assumed to be valid. More validation would be nice, as long as it doesn't add too much overhead.

I'll close this once a new version is rolled out.

**Comment by gvalkov** [comment]
Pushed ansimarkup 0.4.0 with this feature.
