### ISSUE TITLE
Add support for other styles?

### ISSUE THREAD

**Issue by Delgan** [gvalkov/python-ansimarkup#10]
Hi!

I discovered that there were [many different ways](https://en.wikipedia.org/wiki/ANSI_escape_code#CSI_codes) to [stylize the terminal police](https://misc.flogisoft.com/bash/tip_colors_and_formatting).

Among the most used, and most implemented in libraries similar to `ansimarkup`:
* Underline
* Italic
* Strikethrough
* Blink
* Reverse
* Hidden

Downsides:
* Some terminal may not display it correctly
* We may need to manage the combinations of several styles at the same time

Do you think it would make sense to add them to the libraries?

**Comment by gvalkov** [comment]
Hi. I think it makes sense and that it would be useful :+1: 

> Some terminal may not implement it correctly
That's ultimately the concern of the user, imho. Basically, only what `termcolor` implements can be considered universally implemented. 

> We may need to manage the combinations of several styles at the same time.
We can figure that out later on. For now, just allowing something like `<b><u>` for bold-underline is ok (users can still add `<bu>' as a custom tag, if they need it).

**Comment by gvalkov** [comment]
Fixed in #11. Thanks.
