### ISSUE TITLE
Add a `clear()` method to remove all tags

### ISSUE THREAD

**Issue by Delgan** [gvalkov/python-ansimarkup#2]
Hello.

I love your library, very intuitive yet powerful. The perfect way to deal with colored strings in Python. Thanks for the work done!

I thought that a `clear()` method might be useful for removing tags from a string. To give you a concrete use case: this would be handy to configure logging formatters which would write on the terminal (colored) and in a file (without colors).

```python
>>> fmt = "<red>Some</red> <green>colored</green> <unrelated-tag>text</unrelated-tag>"
>>> clear(fmt)
"Some colored <unrelated-tag>text</unrelated-tag>"
```

Do you think it would make sense to include it in your library? I can take care of it if you find it useful.

**Comment by Delgan** [comment]
Closing as such method already exists: `.strip()`.

**Comment by gvalkov** [comment]
Glad to hear that `ansimarkup` is useful to you :+1:
